// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
package io.github.ronjunevaldoz.awake.ui.headless

import io.github.ronjunevaldoz.awake.ui.UiFillRule
import io.github.ronjunevaldoz.awake.ui.UiImageVector
import io.github.ronjunevaldoz.awake.ui.dp
import io.github.ronjunevaldoz.awake.ui.uiImageVector

/** [Heroicons](https://heroicons.com) vector paths, generated from the published SVG sources by
 * `tools/svg_to_ui_image_vector.py` with curves preserved as real cubic Beziers and holes kept
 * as `UiFillRule.EvenOdd` contours. Never hand-edit or hand-transcribe path data here -- re-run
 * the generator instead (see `skills/awake-icon-authoring/SKILL.md`). Grows one glyph at a
 * time, on demand.
 *
 * Nested one object per real Heroicons style+size tier, not a flat glyph list -- Heroicons ships
 * genuinely different path data per tier (24px solid, 20px "mini" solid, 16px "micro" solid), so
 * there is no single correct [UiImageVector] per glyph name. [Solid20Mini] is the only tier
 * generated so far; add further tiers only when an icon actually needs one.
 *
 * No `Outline` tier can exist yet: the icon pipeline is fill-only (no stroke rendering), and the
 * generator rejects stroked SVGs for that reason.
 *
 * A generic, unbranded home for icon vector data -- [io.github.ronjunevaldoz.awake.ui.designsystem
 * .components.ShadcnIcons] is the shadcn-facing, *overridable* pointer registry that defaults to
 * these but doesn't have to stay pinned to them; a caller wanting a different icon set entirely
 * reassigns `ShadcnIcons.xxx` without this object needing to know or care. */
object HeroIcons {
    /** Heroicons' `solid/20/solid` tier ("mini") -- the size real shadcn/ui's own chrome
     * (dropdown/collapsible chevrons, small inline affordances) actually uses. */
    object Solid20Mini {
        /** Heroicons `chevron-down` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronDown: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(5.22f, 8.22f)
                cubicTo(5.5128f, 7.9275f, 5.9872f, 7.9275f, 6.28f, 8.22f)
                lineTo(10f, 11.94f)
                lineTo(13.72f, 8.22f)
                cubicTo(13.907f, 8.0193f, 14.1886f, 7.9368f, 14.4543f, 8.0046f)
                cubicTo(14.72f, 8.0725f, 14.9275f, 8.28f, 14.9954f, 8.5457f)
                cubicTo(15.0632f, 8.8114f, 14.9807f, 9.093f, 14.78f, 9.28f)
                lineTo(10.53f, 13.53f)
                cubicTo(10.2372f, 13.8225f, 9.7628f, 13.8225f, 9.47f, 13.53f)
                lineTo(5.22f, 9.28f)
                cubicTo(4.9275f, 8.9872f, 4.9275f, 8.5128f, 5.22f, 8.22f)
                close()
            }
        }

        /** Heroicons `chevron-up` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronUp: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(9.47f, 6.47f)
                cubicTo(9.7628f, 6.1775f, 10.2372f, 6.1775f, 10.53f, 6.47f)
                lineTo(14.78f, 10.72f)
                cubicTo(14.9807f, 10.907f, 15.0632f, 11.1886f, 14.9954f, 11.4543f)
                cubicTo(14.9275f, 11.72f, 14.72f, 11.9275f, 14.4543f, 11.9954f)
                cubicTo(14.1886f, 12.0632f, 13.907f, 11.9807f, 13.72f, 11.78f)
                lineTo(10f, 8.06f)
                lineTo(6.28f, 11.78f)
                cubicTo(5.9845f, 12.0554f, 5.524f, 12.0472f, 5.2384f, 11.7616f)
                cubicTo(4.9528f, 11.476f, 4.9446f, 11.0155f, 5.22f, 10.72f)
                lineTo(9.47f, 6.47f)
                close()
            }
        }

        /** Heroicons `chevron-right` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronRight: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(8.22f, 5.22f)
                cubicTo(8.5128f, 4.9275f, 8.9872f, 4.9275f, 9.28f, 5.22f)
                lineTo(13.53f, 9.47f)
                cubicTo(13.8225f, 9.7628f, 13.8225f, 10.2372f, 13.53f, 10.53f)
                lineTo(9.28f, 14.78f)
                cubicTo(8.9845f, 15.0554f, 8.524f, 15.0472f, 8.2384f, 14.7616f)
                cubicTo(7.9528f, 14.476f, 7.9446f, 14.0155f, 8.22f, 13.72f)
                lineTo(11.94f, 10f)
                lineTo(8.22f, 6.28f)
                cubicTo(7.9275f, 5.9872f, 7.9275f, 5.5128f, 8.22f, 5.22f)
                close()
            }
        }

        /** Heroicons `chevron-left` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val chevronLeft: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(11.78f, 5.22f)
                cubicTo(12.0725f, 5.5128f, 12.0725f, 5.9872f, 11.78f, 6.28f)
                lineTo(8.06f, 10f)
                lineTo(11.78f, 13.72f)
                cubicTo(11.9807f, 13.907f, 12.0632f, 14.1886f, 11.9954f, 14.4543f)
                cubicTo(11.9275f, 14.72f, 11.72f, 14.9275f, 11.4543f, 14.9954f)
                cubicTo(11.1886f, 15.0632f, 10.907f, 14.9807f, 10.72f, 14.78f)
                lineTo(6.47f, 10.53f)
                cubicTo(6.1775f, 10.2372f, 6.1775f, 9.7628f, 6.47f, 9.47f)
                lineTo(10.72f, 5.22f)
                cubicTo(11.0128f, 4.9275f, 11.4872f, 4.9275f, 11.78f, 5.22f)
                close()
            }
        }

        /** Heroicons `squares-2x2` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val squares2x2: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(4.25f, 2f)
                cubicTo(3.0074f, 2f, 2f, 3.0074f, 2f, 4.25f)
                lineTo(2f, 6.75f)
                cubicTo(2f, 7.9926f, 3.0074f, 9f, 4.25f, 9f)
                lineTo(6.75f, 9f)
                cubicTo(7.9926f, 9f, 9f, 7.9926f, 9f, 6.75f)
                lineTo(9f, 4.25f)
                cubicTo(9f, 3.0074f, 7.9926f, 2f, 6.75f, 2f)
                lineTo(4.25f, 2f)
                close()
                moveTo(4.25f, 11f)
                cubicTo(3.0074f, 11f, 2f, 12.0074f, 2f, 13.25f)
                lineTo(2f, 15.75f)
                cubicTo(2f, 16.9926f, 3.0074f, 18f, 4.25f, 18f)
                lineTo(6.75f, 18f)
                cubicTo(7.9926f, 18f, 9f, 16.9926f, 9f, 15.75f)
                lineTo(9f, 13.25f)
                cubicTo(9f, 12.0074f, 7.9926f, 11f, 6.75f, 11f)
                lineTo(4.25f, 11f)
                close()
                moveTo(13.25f, 2f)
                cubicTo(12.0074f, 2f, 11f, 3.0074f, 11f, 4.25f)
                lineTo(11f, 6.75f)
                cubicTo(11f, 7.9926f, 12.0074f, 9f, 13.25f, 9f)
                lineTo(15.75f, 9f)
                cubicTo(16.9926f, 9f, 18f, 7.9926f, 18f, 6.75f)
                lineTo(18f, 4.25f)
                cubicTo(18f, 3.0074f, 16.9926f, 2f, 15.75f, 2f)
                lineTo(13.25f, 2f)
                close()
                moveTo(13.25f, 11f)
                cubicTo(12.0074f, 11f, 11f, 12.0074f, 11f, 13.25f)
                lineTo(11f, 15.75f)
                cubicTo(11f, 16.9926f, 12.0074f, 18f, 13.25f, 18f)
                lineTo(15.75f, 18f)
                cubicTo(16.9926f, 18f, 18f, 16.9926f, 18f, 15.75f)
                lineTo(18f, 13.25f)
                cubicTo(18f, 12.0074f, 16.9926f, 11f, 15.75f, 11f)
                lineTo(13.25f, 11f)
                close()
            }
        }

        /** Heroicons `square-3-stack-3d` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val square3Stack3d: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(3.196f, 12.87f)
                lineTo(2.371f, 13.353f)
                cubicTo(2.1414f, 13.4876f, 2.0003f, 13.7338f, 2.0003f, 14f)
                cubicTo(2.0003f, 14.2662f, 2.1414f, 14.5124f, 2.371f, 14.647f)
                lineTo(9.621f, 18.897f)
                cubicTo(9.8551f, 19.0341f, 10.1449f, 19.0341f, 10.379f, 18.897f)
                lineTo(17.629f, 14.647f)
                cubicTo(17.8586f, 14.5124f, 17.9997f, 14.2662f, 17.9997f, 14f)
                cubicTo(17.9997f, 13.7338f, 17.8586f, 13.4876f, 17.629f, 13.353f)
                lineTo(16.804f, 12.869f)
                lineTo(11.138f, 16.191f)
                cubicTo(10.4353f, 16.603f, 9.5647f, 16.603f, 8.862f, 16.191f)
                lineTo(3.196f, 12.87f)
                close()
            }
            path {
                moveTo(3.196f, 8.87f)
                lineTo(2.371f, 9.353f)
                cubicTo(2.1414f, 9.4876f, 2.0003f, 9.7338f, 2.0003f, 10f)
                cubicTo(2.0003f, 10.2662f, 2.1414f, 10.5124f, 2.371f, 10.647f)
                lineTo(9.621f, 14.897f)
                cubicTo(9.8551f, 15.0341f, 10.1449f, 15.0341f, 10.379f, 14.897f)
                lineTo(17.629f, 10.647f)
                cubicTo(17.8586f, 10.5124f, 17.9997f, 10.2662f, 17.9997f, 10f)
                cubicTo(17.9997f, 9.7338f, 17.8586f, 9.4876f, 17.629f, 9.353f)
                lineTo(16.804f, 8.869f)
                lineTo(11.138f, 12.191f)
                cubicTo(10.4353f, 12.603f, 9.5647f, 12.603f, 8.862f, 12.191f)
                lineTo(3.196f, 8.87f)
                close()
            }
            path {
                moveTo(10.38f, 1.103f)
                cubicTo(10.1454f, 0.9651f, 9.8546f, 0.9651f, 9.62f, 1.103f)
                lineTo(2.37f, 5.353f)
                cubicTo(2.1404f, 5.4876f, 1.9993f, 5.7338f, 1.9993f, 6f)
                cubicTo(1.9993f, 6.2662f, 2.1404f, 6.5124f, 2.37f, 6.647f)
                lineTo(9.62f, 10.897f)
                cubicTo(9.8546f, 11.0349f, 10.1454f, 11.0349f, 10.38f, 10.897f)
                lineTo(17.63f, 6.647f)
                cubicTo(17.8596f, 6.5124f, 18.0007f, 6.2662f, 18.0007f, 6f)
                cubicTo(18.0007f, 5.7338f, 17.8596f, 5.4876f, 17.63f, 5.353f)
                lineTo(10.38f, 1.103f)
                close()
            }
        }

        /** Heroicons `table-cells` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val tableCells: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(0.99f, 5.24f)
                cubicTo(0.9926f, 4.6433f, 1.2322f, 4.072f, 1.6561f, 3.6519f)
                cubicTo(2.0799f, 3.2318f, 2.6533f, 2.9973f, 3.25f, 3f)
                lineTo(16.75f, 3f)
                cubicTo(17.9926f, 3f, 19f, 4.0074f, 19f, 5.25f)
                lineTo(19.01f, 14.75f)
                cubicTo(19.01f, 15.9926f, 18.0026f, 17f, 16.76f, 17f)
                lineTo(3.26f, 17f)
                cubicTo(2.0134f, 16.9962f, 1.0038f, 15.9866f, 1f, 14.74f)
                lineTo(0.99f, 5.24f)
                close()
                moveTo(9.25f, 14.76f)
                lineTo(9.25f, 14.135f)
                cubicTo(9.25f, 13.7208f, 8.9142f, 13.385f, 8.5f, 13.385f)
                lineTo(3.25f, 13.385f)
                cubicTo(2.8358f, 13.385f, 2.5f, 13.7208f, 2.5f, 14.135f)
                lineTo(2.5f, 14.75f)
                cubicTo(2.5f, 15.164f, 2.836f, 15.5f, 3.25f, 15.5f)
                lineTo(8.623f, 15.5f)
                cubicTo(8.9848f, 15.4398f, 9.2501f, 15.1268f, 9.25f, 14.76f)
                close()
                moveTo(10.75f, 14.76f)
                cubicTo(10.7499f, 15.1268f, 11.0152f, 15.4398f, 11.377f, 15.5f)
                lineTo(16.75f, 15.5f)
                cubicTo(17.1642f, 15.5f, 17.5f, 15.1642f, 17.5f, 14.75f)
                lineTo(17.5f, 14.135f)
                cubicTo(17.5f, 13.7208f, 17.1642f, 13.385f, 16.75f, 13.385f)
                lineTo(11.5f, 13.385f)
                cubicTo(11.0858f, 13.385f, 10.75f, 13.7208f, 10.75f, 14.135f)
                lineTo(10.75f, 14.76f)
                close()
                moveTo(17.5f, 11.13f)
                lineTo(17.5f, 10.505f)
                cubicTo(17.5f, 10.0908f, 17.1642f, 9.755f, 16.75f, 9.755f)
                lineTo(11.5f, 9.755f)
                cubicTo(11.0858f, 9.755f, 10.75f, 10.0908f, 10.75f, 10.505f)
                lineTo(10.75f, 11.13f)
                cubicTo(10.75f, 11.544f, 11.086f, 11.88f, 11.5f, 11.88f)
                lineTo(16.75f, 11.88f)
                cubicTo(17.1642f, 11.88f, 17.5f, 11.5442f, 17.5f, 11.13f)
                close()
                moveTo(9.25f, 11.13f)
                lineTo(9.25f, 10.505f)
                cubicTo(9.25f, 10.0908f, 8.9142f, 9.755f, 8.5f, 9.755f)
                lineTo(3.25f, 9.755f)
                cubicTo(2.8358f, 9.755f, 2.5f, 10.0908f, 2.5f, 10.505f)
                lineTo(2.5f, 11.13f)
                cubicTo(2.5f, 11.544f, 2.836f, 11.88f, 3.25f, 11.88f)
                lineTo(8.5f, 11.88f)
                cubicTo(8.9142f, 11.88f, 9.25f, 11.5442f, 9.25f, 11.13f)
                close()
                moveTo(17.5f, 7.5f)
                lineTo(17.5f, 6.875f)
                cubicTo(17.5f, 6.4608f, 17.1642f, 6.125f, 16.75f, 6.125f)
                lineTo(11.5f, 6.125f)
                cubicTo(11.0858f, 6.125f, 10.75f, 6.4608f, 10.75f, 6.875f)
                lineTo(10.75f, 7.5f)
                cubicTo(10.75f, 7.914f, 11.086f, 8.25f, 11.5f, 8.25f)
                lineTo(16.75f, 8.25f)
                cubicTo(17.1642f, 8.25f, 17.5f, 7.9142f, 17.5f, 7.5f)
                close()
                moveTo(9.25f, 7.5f)
                lineTo(9.25f, 6.875f)
                cubicTo(9.25f, 6.4608f, 8.9142f, 6.125f, 8.5f, 6.125f)
                lineTo(3.25f, 6.125f)
                cubicTo(2.8358f, 6.125f, 2.5f, 6.4608f, 2.5f, 6.875f)
                lineTo(2.5f, 7.5f)
                cubicTo(2.5f, 7.914f, 2.836f, 8.25f, 3.25f, 8.25f)
                lineTo(8.5f, 8.25f)
                cubicTo(8.9142f, 8.25f, 9.25f, 7.9142f, 9.25f, 7.5f)
                close()
            }
        }

        /** Heroicons `globe-alt` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val globeAlt: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(16.555f, 5.412f)
                cubicTo(15.6784f, 4.1612f, 14.4632f, 3.1864f, 13.052f, 2.602f)
                cubicTo(13.843f, 3.9937f, 14.4045f, 5.5037f, 14.715f, 7.074f)
                cubicTo(15.4059f, 6.6124f, 16.0257f, 6.0525f, 16.555f, 5.412f)
                close()
                moveTo(13.326f, 7.825f)
                cubicTo(12.9874f, 5.7375f, 12.1606f, 3.7595f, 10.913f, 2.052f)
                cubicTo(10.3063f, 1.9831f, 9.6937f, 1.9831f, 9.087f, 2.052f)
                cubicTo(7.8394f, 3.7595f, 7.0126f, 5.7375f, 6.674f, 7.825f)
                cubicTo(7.7258f, 8.272f, 8.8572f, 8.5016f, 10f, 8.5f)
                cubicTo(11.18f, 8.5f, 12.304f, 8.26f, 13.326f, 7.825f)
                close()
                moveTo(6.514f, 9.376f)
                cubicTo(7.6295f, 9.7902f, 8.8101f, 10.0015f, 10f, 10f)
                cubicTo(11.226f, 10f, 12.4f, 9.78f, 13.486f, 9.376f)
                cubicTo(13.5451f, 10.6392f, 13.427f, 11.9045f, 13.135f, 13.135f)
                cubicTo(12.1078f, 13.3785f, 11.0557f, 13.501f, 10f, 13.5f)
                cubicTo(8.921f, 13.5f, 7.872f, 13.373f, 6.866f, 13.134f)
                cubicTo(6.5738f, 11.9039f, 6.4553f, 10.639f, 6.514f, 9.376f)
                close()
                moveTo(5.285f, 7.074f)
                cubicTo(5.5956f, 5.504f, 6.1571f, 3.9944f, 6.948f, 2.603f)
                cubicTo(5.5368f, 3.1874f, 4.3216f, 4.1622f, 3.445f, 5.413f)
                cubicTo(3.974f, 6.051f, 4.594f, 6.612f, 5.285f, 7.073f)
                close()
                moveTo(17.334f, 6.798f)
                cubicTo(17.8993f, 8.0912f, 18.1111f, 9.5112f, 17.948f, 10.913f)
                cubicTo(16.9707f, 11.6265f, 15.9018f, 12.205f, 14.77f, 12.633f)
                cubicTo(15f, 11.3333f, 15.0585f, 10.009f, 14.944f, 8.694f)
                cubicTo(15.8326f, 8.1874f, 16.6385f, 7.548f, 17.334f, 6.798f)
                close()
                moveTo(2.666f, 6.798f)
                cubicTo(3.3615f, 7.548f, 4.1674f, 8.1874f, 5.056f, 8.694f)
                cubicTo(4.9426f, 10.0093f, 5.0011f, 11.3338f, 5.23f, 12.634f)
                cubicTo(4.0982f, 12.206f, 3.0293f, 11.6274f, 2.052f, 10.914f)
                cubicTo(1.8892f, 9.5121f, 2.1014f, 8.0921f, 2.667f, 6.799f)
                close()
                moveTo(10f, 15f)
                cubicTo(10.898f, 15f, 11.778f, 14.921f, 12.633f, 14.77f)
                cubicTo(12.205f, 15.9018f, 11.6264f, 16.9707f, 10.913f, 17.948f)
                cubicTo(10.3063f, 18.0168f, 9.6937f, 18.0168f, 9.087f, 17.948f)
                cubicTo(8.3735f, 16.9707f, 7.795f, 15.9018f, 7.367f, 14.77f)
                cubicTo(8.222f, 14.921f, 9.102f, 15f, 10f, 15f)
                close()
                moveTo(14.357f, 14.357f)
                cubicTo(14.0361f, 15.4156f, 13.5984f, 16.4352f, 13.052f, 17.397f)
                cubicTo(15.0193f, 16.5823f, 16.5823f, 15.0193f, 17.397f, 13.052f)
                cubicTo(16.444f, 13.594f, 15.426f, 14.033f, 14.357f, 14.357f)
                close()
                moveTo(6.948f, 17.397f)
                cubicTo(4.9807f, 16.5823f, 3.4177f, 15.0193f, 2.603f, 13.052f)
                cubicTo(3.556f, 13.594f, 4.574f, 14.033f, 5.643f, 14.357f)
                cubicTo(5.9639f, 15.4156f, 6.4016f, 16.4352f, 6.948f, 17.397f)
                close()
            }
        }

        /** Heroicons `clock` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val clock: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(10f, 18f)
                cubicTo(14.4183f, 18f, 18f, 14.4183f, 18f, 10f)
                cubicTo(18f, 5.5817f, 14.4183f, 2f, 10f, 2f)
                cubicTo(5.5817f, 2f, 2f, 5.5817f, 2f, 10f)
                cubicTo(2f, 14.4183f, 5.5817f, 18f, 10f, 18f)
                close()
                moveTo(10.75f, 5f)
                cubicTo(10.75f, 4.5858f, 10.4142f, 4.25f, 10f, 4.25f)
                cubicTo(9.5858f, 4.25f, 9.25f, 4.5858f, 9.25f, 5f)
                lineTo(9.25f, 10f)
                cubicTo(9.25f, 10.414f, 9.586f, 10.75f, 10f, 10.75f)
                lineTo(14f, 10.75f)
                cubicTo(14.4142f, 10.75f, 14.75f, 10.4142f, 14.75f, 10f)
                cubicTo(14.75f, 9.5858f, 14.4142f, 9.25f, 14f, 9.25f)
                lineTo(10.75f, 9.25f)
                lineTo(10.75f, 5f)
                close()
            }
        }

        /** Heroicons `arrow-path` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val arrowPath: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path {
                moveTo(15.312f, 11.424f)
                cubicTo(14.8034f, 13.3218f, 13.3211f, 14.8042f, 11.4233f, 15.3128f)
                cubicTo(9.5255f, 15.8214f, 7.5005f, 15.2791f, 6.111f, 13.89f)
                lineTo(5.799f, 13.579f)
                lineTo(8.232f, 13.579f)
                cubicTo(8.6462f, 13.579f, 8.982f, 13.2432f, 8.982f, 12.829f)
                cubicTo(8.982f, 12.4148f, 8.6462f, 12.079f, 8.232f, 12.079f)
                lineTo(3.989f, 12.079f)
                cubicTo(3.5748f, 12.079f, 3.239f, 12.4148f, 3.239f, 12.829f)
                lineTo(3.239f, 17.071f)
                cubicTo(3.239f, 17.4852f, 3.5748f, 17.821f, 3.989f, 17.821f)
                cubicTo(4.4032f, 17.821f, 4.739f, 17.4852f, 4.739f, 17.071f)
                lineTo(4.739f, 14.641f)
                lineTo(5.049f, 14.951f)
                cubicTo(6.8173f, 16.7198f, 9.3951f, 17.4107f, 11.811f, 16.7634f)
                cubicTo(14.2269f, 16.1161f, 16.1139f, 14.229f, 16.761f, 11.813f)
                cubicTo(16.8687f, 11.4129f, 16.6316f, 11.0012f, 16.2315f, 10.8935f)
                cubicTo(15.8314f, 10.7858f, 15.4197f, 11.0229f, 15.312f, 11.423f)
                close()
                moveTo(16.542f, 7.701f)
                cubicTo(16.6823f, 7.5603f, 16.7611f, 7.3697f, 16.761f, 7.171f)
                lineTo(16.761f, 2.929f)
                cubicTo(16.761f, 2.5148f, 16.4252f, 2.179f, 16.011f, 2.179f)
                cubicTo(15.5968f, 2.179f, 15.261f, 2.5148f, 15.261f, 2.929f)
                lineTo(15.261f, 5.36f)
                lineTo(14.951f, 5.05f)
                cubicTo(13.1827f, 3.2812f, 10.6049f, 2.5903f, 8.189f, 3.2376f)
                cubicTo(5.7731f, 3.8849f, 3.8861f, 5.772f, 3.239f, 8.188f)
                cubicTo(3.1603f, 8.4497f, 3.2302f, 8.7334f, 3.4214f, 8.9287f)
                cubicTo(3.6125f, 9.1239f, 3.8948f, 9.1997f, 4.158f, 9.1266f)
                cubicTo(4.4213f, 9.0534f, 4.624f, 8.8429f, 4.687f, 8.577f)
                cubicTo(5.1949f, 6.6782f, 6.6776f, 5.1948f, 8.5761f, 4.6859f)
                cubicTo(10.4746f, 4.177f, 12.5004f, 4.7199f, 13.89f, 6.11f)
                lineTo(14.201f, 6.42f)
                lineTo(11.769f, 6.42f)
                cubicTo(11.3548f, 6.42f, 11.019f, 6.7558f, 11.019f, 7.17f)
                cubicTo(11.019f, 7.5842f, 11.3548f, 7.92f, 11.769f, 7.92f)
                lineTo(16.012f, 7.92f)
                cubicTo(16.2107f, 7.9201f, 16.4013f, 7.8413f, 16.542f, 7.701f)
                close()
            }
        }

        /** Heroicons `camera` (20/solid "mini"), generated by tools/svg_to_ui_image_vector.py -- do not hand-edit. */
        val camera: UiImageVector = uiImageVector(
            defaultWidth = 16f.dp,
            defaultHeight = 16f.dp,
            viewportWidth = 20f,
            viewportHeight = 20f,
        ) {
            path(fillRule = UiFillRule.EvenOdd) {
                moveTo(1f, 8f)
                cubicTo(1f, 6.8954f, 1.8954f, 6f, 3f, 6f)
                lineTo(3.93f, 6f)
                cubicTo(4.5986f, 6.0001f, 5.223f, 5.6661f, 5.594f, 5.11f)
                lineTo(6.406f, 3.89f)
                cubicTo(6.777f, 3.3339f, 7.4014f, 2.9999f, 8.07f, 3f)
                lineTo(11.93f, 3f)
                cubicTo(12.5986f, 2.9999f, 13.223f, 3.3339f, 13.594f, 3.89f)
                lineTo(14.406f, 5.11f)
                cubicTo(14.777f, 5.6661f, 15.4014f, 6.0001f, 16.07f, 6f)
                lineTo(17f, 6f)
                cubicTo(18.1046f, 6f, 19f, 6.8954f, 19f, 8f)
                lineTo(19f, 15f)
                cubicTo(19f, 16.1046f, 18.1046f, 17f, 17f, 17f)
                lineTo(3f, 17f)
                cubicTo(1.8954f, 17f, 1f, 16.1046f, 1f, 15f)
                lineTo(1f, 8f)
                close()
                moveTo(14.5f, 11f)
                cubicTo(14.5f, 13.4853f, 12.4853f, 15.5f, 10f, 15.5f)
                cubicTo(7.5147f, 15.5f, 5.5f, 13.4853f, 5.5f, 11f)
                cubicTo(5.5f, 8.5147f, 7.5147f, 6.5f, 10f, 6.5f)
                cubicTo(12.4853f, 6.5f, 14.5f, 8.5147f, 14.5f, 11f)
                close()
                moveTo(10f, 14f)
                cubicTo(11.6569f, 14f, 13f, 12.6569f, 13f, 11f)
                cubicTo(13f, 9.3431f, 11.6569f, 8f, 10f, 8f)
                cubicTo(8.3431f, 8f, 7f, 9.3431f, 7f, 11f)
                cubicTo(7f, 12.6569f, 8.3431f, 14f, 10f, 14f)
                close()
            }
        }
    }
}
