// Copyright (c) Ron June Valdoz
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED FILE -- do not hand-edit.
// Generated by tools/extract_shadcn_tokens.py from shadcn-ui/ui @ 6261bd89f72d794aea491482cc2acfd8dc3d63e2
// (apps/v4/registry/themes.ts, theme "neutral", new-york-v4 style -- Awake's
// ShadcnBaseColor.Neutral counterpart). Re-run tools/fetch_shadcn_reference.sh to move the
// pinned checkout, then this script to refresh. See docs/reference/shadcn-reference-pipeline.md.
package io.github.ronjunevaldoz.awake.ui.designsystem

/** One real shadcn OKLCH CSS custom property value: `oklch(lightness chroma hueDegrees [/ alpha%])`. */
data class ShadcnReferenceOklch(
    val lightness: Float,
    val chroma: Float,
    val hueDegrees: Float,
    val alpha: Float = 1f,
)

/**
 * Real shadcn/ui "neutral" base-color ground truth -- see file header for provenance.
 * Map keys are the CSS custom property name verbatim (`"card-foreground"`, not `cardForeground`)
 * so they stay directly greppable against shadcn's own `--card-foreground` var.
 */
object ShadcnReferenceTokens {
    const val PINNED_SHA: String = "6261bd89f72d794aea491482cc2acfd8dc3d63e2"
    const val RADIUS_REM: Float = 0.625f
    val OTHER_SIZES_REM: Map<String, Float> = emptyMap()

    val light: Map<String, ShadcnReferenceOklch> = mapOf(
        "background" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f),
        "foreground" to ShadcnReferenceOklch(0.145f, 0.0f, 0.0f),
        "card" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f),
        "card-foreground" to ShadcnReferenceOklch(0.145f, 0.0f, 0.0f),
        "popover" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f),
        "popover-foreground" to ShadcnReferenceOklch(0.145f, 0.0f, 0.0f),
        "primary" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "primary-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "secondary" to ShadcnReferenceOklch(0.97f, 0.0f, 0.0f),
        "secondary-foreground" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "muted" to ShadcnReferenceOklch(0.97f, 0.0f, 0.0f),
        "muted-foreground" to ShadcnReferenceOklch(0.556f, 0.0f, 0.0f),
        "accent" to ShadcnReferenceOklch(0.97f, 0.0f, 0.0f),
        "accent-foreground" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "destructive" to ShadcnReferenceOklch(0.577f, 0.245f, 27.325f),
        "border" to ShadcnReferenceOklch(0.922f, 0.0f, 0.0f),
        "input" to ShadcnReferenceOklch(0.922f, 0.0f, 0.0f),
        "ring" to ShadcnReferenceOklch(0.708f, 0.0f, 0.0f),
        "chart-1" to ShadcnReferenceOklch(0.87f, 0.0f, 0.0f),
        "chart-2" to ShadcnReferenceOklch(0.556f, 0.0f, 0.0f),
        "chart-3" to ShadcnReferenceOklch(0.439f, 0.0f, 0.0f),
        "chart-4" to ShadcnReferenceOklch(0.371f, 0.0f, 0.0f),
        "chart-5" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "sidebar" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "sidebar-foreground" to ShadcnReferenceOklch(0.145f, 0.0f, 0.0f),
        "sidebar-primary" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "sidebar-primary-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "sidebar-accent" to ShadcnReferenceOklch(0.97f, 0.0f, 0.0f),
        "sidebar-accent-foreground" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "sidebar-border" to ShadcnReferenceOklch(0.922f, 0.0f, 0.0f),
        "sidebar-ring" to ShadcnReferenceOklch(0.708f, 0.0f, 0.0f),
    )

    val dark: Map<String, ShadcnReferenceOklch> = mapOf(
        "background" to ShadcnReferenceOklch(0.145f, 0.0f, 0.0f),
        "foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "card" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "card-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "popover" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "popover-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "primary" to ShadcnReferenceOklch(0.922f, 0.0f, 0.0f),
        "primary-foreground" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "secondary" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "secondary-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "muted" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "muted-foreground" to ShadcnReferenceOklch(0.708f, 0.0f, 0.0f),
        "accent" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "accent-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "destructive" to ShadcnReferenceOklch(0.704f, 0.191f, 22.216f),
        "border" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f, 0.1f),
        "input" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f, 0.15f),
        "ring" to ShadcnReferenceOklch(0.556f, 0.0f, 0.0f),
        "chart-1" to ShadcnReferenceOklch(0.87f, 0.0f, 0.0f),
        "chart-2" to ShadcnReferenceOklch(0.556f, 0.0f, 0.0f),
        "chart-3" to ShadcnReferenceOklch(0.439f, 0.0f, 0.0f),
        "chart-4" to ShadcnReferenceOklch(0.371f, 0.0f, 0.0f),
        "chart-5" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "sidebar" to ShadcnReferenceOklch(0.205f, 0.0f, 0.0f),
        "sidebar-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "sidebar-primary" to ShadcnReferenceOklch(0.488f, 0.243f, 264.376f),
        "sidebar-primary-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "sidebar-accent" to ShadcnReferenceOklch(0.269f, 0.0f, 0.0f),
        "sidebar-accent-foreground" to ShadcnReferenceOklch(0.985f, 0.0f, 0.0f),
        "sidebar-border" to ShadcnReferenceOklch(1.0f, 0.0f, 0.0f, 0.1f),
        "sidebar-ring" to ShadcnReferenceOklch(0.556f, 0.0f, 0.0f),
    )
}
